python main.py^
 --name="t5-default-pretrain"^
 --lr=2e-5^
 --epochs=1^
 --lr_scheduler=False^
 --model_checkpoint="google/t5-v1_1-small"^
 --tokenizer_checkpoint="google/t5-v1_1-small"^
 --train_dataset="./etc/tgt-beta-0.85t-86k"^
 --max_seq_len=512^
 --max_ans_len=128^
 --seed=0^
 --runmode="pretrain"^
 --lora=False^
 --savedir="./test_path"^
