[mode]
runmode = "bart-finetune"

[model]
name = "bart-base-sft-default"
max_seq_len = 1024
checkpoint = "facebook/bart-base"

[dataset]
repository = "test-assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "facebook/bart-base"

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = false
num_epochs = 12
training_batch_size = 4
validation_batch_size = 4
seed = 0

[misc]
save_dir = "./"