[mode]
runmode = "bert-finetune"
eval_after_training = true

[model]
name = "biobert-base-sft-default"
max_seq_len = 512
checkpoint = "dmis-lab/biobert-base-cased-v1.2"
bitfit = false

[dataset]
repository = "test-assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "dmis-lab/biobert-base-cased-v1.2"
append_special_tokens=false

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = true
num_epochs = 12
training_batch_size = 8
validation_batch_size = 8
seed = 0

[misc]
save_dir = "./"