[mode]
runmode = "bert-finetune"
eval_after_training = true

[model]
name = "biobert-base-sft-seed100"
max_seq_len = 512
checkpoint = "assets/models/dmis-lab/biobert-v1.1"
bitfit = false

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/dmis-lab/biobert-v1.1"
append_special_tokens=false

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = true
num_epochs = 12
training_batch_size = 8
validation_batch_size = 8
seed = 100

[misc]
save_dir = "./"