# pubmedbert supervised fine-tuning for OQA
[mode]
runmode = "bert-finetune"

[model]
name = "biobert-base-sft-default"
max_seq_len = 512
checkpoint = "dmis-lab/biobert-base-cased-v1.2"
bitfit = false

[dataset]
train_dataset_path="./tmp/bin/train"
val_dataset_path="./tmp/bin/val"
test_dataset_path="./tmp/bin/test"


[tokenizer]
checkpoint = "dmis-lab/biobert-base-cased-v1.2"

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = true
num_epochs = 10
training_batch_size = 8
validation_batch_size = 8
seed = 0

[misc]
save_dir = "./"