[mode]
runmode = "bart-finetune"
eval_after_training = true

[model]
name = "biobart-base-sft-seed100"
max_seq_len = 1024
max_ans_len = 256
checkpoint = "assets/models/GanjinZero/biobart-base"

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/GanjinZero/biobart-base"

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = false
num_epochs = 12
training_batch_size = 4
validation_batch_size = 4
seed = 100

[misc]
save_dir = "./"