[mode]
runmode = "t5-evaluate"

[model]
name = "t5-DEBUG"
max_seq_len = 768
max_ans_len = 128
checkpoint = "outputs/t5-base-sft-default-04-07-2023_09-56-16/checkpoint-bestf1"

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/t5-base"

[hyperparameters]
validation_batch_size = 4
seed = 0

[misc]
save_dir = "./"