[mode]
runmode = "bart-evaluate"

[model]
name = "bart-DEBUG"
max_seq_len = 1024
max_ans_len = 256
checkpoint = "outputs/bart-base-sft-default-04-07-2023_09-56-15/checkpoint-bestf1"

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/facebook/bart-base"

[hyperparameters]
validation_batch_size = 4
seed = 0

[misc]
save_dir = "./"