[mode]
runmode = "bert-finetune"
eval_after_training = true

[model]
name = "pubmedbert-base_squad-sft-seed100"
max_seq_len = 512
checkpoint = "mr-assets/models/m-rousseau/pubmedbert-base-squad2ep"
bitfit = false

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
append_special_tokens=false

[hyperparameters]
learning_rate = 2e-5
learning_rate_scheduler = true
num_epochs = 12
training_batch_size = 8
validation_batch_size = 8
seed = 100

[misc]
save_dir = "./"