[mode]
runmode = "t5-finetune"
eval_after_training = true

[model]
name = "scifive-base-sft-seed100"
max_seq_len = 1024
max_ans_len = 128
checkpoint = "assets/models/razent/SciFive-base-Pubmed_PMC"

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/razent/SciFive-base-Pubmed_PMC"

[hyperparameters]
learning_rate = 1e-4
learning_rate_scheduler = false
num_epochs = 12
training_batch_size = 4
validation_batch_size = 4
seed = 100

[misc]
save_dir = "./"