[mode]
runmode = "t5-finetune"
eval_after_training = true

[model]
name = "t5-base-sft-default"
max_seq_len = 768
max_ans_len = 128
checkpoint = "assets/models/t5-base"

[dataset]
repository = "assets/datasets/m-rousseau/oqa-v1"

[tokenizer]
checkpoint = "assets/models/t5-base"

[hyperparameters]
learning_rate = 1e-4
learning_rate_scheduler = false
num_epochs = 12
training_batch_size = 4
validation_batch_size = 4
seed = 0

[misc]
save_dir = "./"