python main.py^
 --name="bart-test"^
 --lr=3e-4^
 --epochs=1^
 --lr_scheduler=True^
 --model_checkpoint="facebook/bart-base"^
 --tokenizer_checkpoint="facebook/bart-base"^
 --train_dataset="./tmp/bin/train"^
 --val_dataset="./tmp/bin/val"^
 --max_seq_len=512^
 --max_ans_len=128^
 --seed=0^
 --runmode="bart-finetune"^
 --savedir="./test_path"^
